topic:
  name: cgisolution-productbundles
  partitions-num: 3
  replication-factor: 1
server:
  port: 9080
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: spring-kafka
      authentication-database: admin
      username: user
      password: password
  kafka:
    bootstrap-servers:
      - localhost:29092
    properties:
      schema.registry.url: http://localhost:8081
    consumer:
      specific:
        avro:
          reader: true
      enable:
        auto:
          commit: false
      group-id: client-group-2
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        interceptor.classes: io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        interceptor.classes: io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor
    template:
      default-topic:
logging:
  level:
    root: info
